# Generated by Django 4.0.4 on 2022-05-02 07:51

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(max_length=50)),
                ('product_price', models.PositiveIntegerField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=product.models.Product.nameFile)),
            ],
        ),
    ]
